Linear Search completed
ohbus/algorithms pull request #8
Opened 2020-10-03 05:22 UTC by Souph

### Pull request title
- [ ] Clearly and concisely describes what it does
- [ ] Refer to the issue that it solves, if available

### Pull request description

- [ ] Describes the main changes that come with the pull request
- [ ] Any relevant additional information is provided

2020-10-03 05:31 UTC, ohbus requested changes
Please run `./mvnw spotless:apply` to format the code.

2020-10-03 05:31 UTC, ohbus commented on src/main/java/xyz/subho/algorithms/search/LinearSearch.java
> +}
Add a new line at the end of the file.

2020-10-03 06:10 UTC, Souph commented
Linear search update 2.0

2020-10-03 06:27 UTC, ohbus approved these changes

2020-10-03 06:28 UTC, merged

2021-01-04 15:11 UTC, ohbus commented
@all-contributors please add @Souph for code

2021-01-04 15:15 UTC, ohbus commented
@all-contributors please add @Souph for code